#!/bin/sh

echo -n 'Starting keystone: '
docker run -d --name keystone -P larsks/keystone
keystone_server=$(
docker port keystone 35357
)

if ! [ "$keystone_server" ]; then
	echo "ERROR: unable to determine keystone server ip and port" >&2
	exit 1
fi

echo "Waiting for keystone server at $keystone_server to settle."
while ! curl -o /dev/null -s -f http://$keystone_server; do
	sleep 1
done


echo -n 'Starting rabbitmq: '
docker run -d --name rabbitmq larsks/rabbitmq
echo -n 'Starting glance: '
docker run -d --name glance \
	--link keystone:keystone \
	--link rabbitmq:amqphost \
	larsks/glance
echo -n 'Starting nova: '
docker run -d --name nova \
	--link keystone:keystone \
	--link rabbitmq:amqphost \
	--link glance:glance \
	larsks/nova-controller

echo 'Initializing keystone.'
docker run --rm \
	--link keystone:keystone \
	--link glance:glance \
	--link nova:nova \
	larsks/os-apiclient /bin/sh /root/setup-keystone.sh
docker run --rm \
	--link keystone:keystone \
	--link glance:glance \
	--link nova:nova \
	larsks/os-apiclient /bin/sh /root/setup-glance.sh
docker run --rm \
	--link keystone:keystone \
	--link glance:glance \
	--link nova:nova \
	larsks/os-apiclient /bin/sh /root/setup-nova.sh

